export const profiles = [
    {
        firstName: 'Graeme',
        lastName: 'Bunton',
        bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        socials: {
        twitter: '',
        instagram: '',
        website: '',
        other: '',
        }
        },
        {
        firstName: 'Trina',
        lastName: 'Hogg',
        bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        socials: {
        twitter: '',
        instagram: '',
        website: '',
        other: '',
        }
        },
        {
        firstName: 'Matt',
        lastName: 'Lemche',
        bio:'',
        socials: {
        twitter: 'https://twitter.com/MattLemche',
        instagram: '',
        website: 'https://mattlemche.com',
        other: '',
        }
        },
        {
        firstName: 'Nadia',
        lastName: 'Nascimento',
        bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        socials: {
        twitter: '',
        instagram: '',
        website: '',
        other: '',
        }
        },
        {
        firstName: 'Marguerite',
        lastName: 'Moreau',
        bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        socials: {
        twitter: '',
        instagram: '',
        website: '',
        other: '',
        }
        },
        {
        firstName: 'Chris',
        lastName: 'Redman',
        bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        socials: {
        twitter: '',
        instagram: '',
        website: '',
        other: '',
        }
        },
        
];

export const decadesSupporters = [
'A.J. Bond',
'Adam Strand',
'Alanna Banks',
'Alex M Richmond',
'Allison Villa',
'Alo Maiu',
'Andrew Raponi',
'Angela Heslop',
'Anmatthe',
'Anne Hochberg',
'Armelle Solelhac & SWiTCH Inc.',
'Arun Brahmbhatt',
'Ashleigh Gardner',
'Aubrey Nealon',
'Barry J. Stiefel',
'Ben Jones',
'Beth Coish',
'Bistra',
'Nicole Dalton',
'Brendan Jeffers',
'Brian Kwan',
'Bryant Parson',
'Calvin Lee Reeder',
'Carolyn Cay',
'Casey Margolis',
'Celia Grant',
'Charlotte Dobo',
'Cheryl & Wayne Morishita',
'Christina Bennett',
'Christine Horne',
'chuck bergman',
'Conrad Leach',
'Courtney Yuchtman',
'Dale Cox',
'Dalia Moftah',
'Danny McHugh',
'David Levy',
'David McFadzean',
'drake doremus',
'Elaine Semanik',
'Eli Herron',
'Emily Adams',
'Emma Campbell',
'Eugenie von Tunzelmann',
'Foster Burden c/o Paedea',
'Frank R Cetera',
'Frank Stratton',
'Gabriel Botnick',
'Grace Carter',
'Greg White',
'Griff Foxley',
'Heather Allisonhames',
'Heather Blair',
'Heather Thompson',
'Hilda Rasula',
'Holly Sumner',
'Hugh Dillon',
'Ivan Kalmar',
'James Marlin',
'Jamie Madge',
'Janice Y. Perez',
'Jeff Black',
'jeffrey t brown',
'Jennifer Lemche',
'Jennifer Scott',
'Jeremy Larson',
'Jesse Dybenko',
'JESSE MACHT',
'Jesse Suchmann',
'Joe Matoske',
'Joe Mei',
'John Cash',
'Joni McKervey',
'Jovanna Scorsone',
'Judy and Mike Lemche',
'Julie Janish',
'Justin Shubert',
'Kabira Stokes',
'karen Hughes',
'Kassem Gharaibeh',
'Kat & George Anderson',
'Kate Mucherino in mem. Of Mom Pat Hustek',
'Kate Willoughby',
'Keiron Waites',
'Ken Stern',
'Kenzie Ryder',
'Kerrie Keane',
'Kerry Shaw',
'Kishwar Iqbal',
'Konstadinos Kurelias',
'Krista Ricciattie',
'Kristen Corvers',
'Kristopher Turner',
'Kristy Clarke',
'Laura Ouellette',
'Laura Raymond',
'Lauren Black',
'Lena Georgas',
'Lindy booth',
'Lisa Bunton',
'Logan St. Clair',
'Lois Brown',
'Luke Frydenger',
'M. Bailey',
'Mackenzie Korb',
'Martha Preciado R.',
'Mary Anne De Iulis',
'Matt',
'Matt Aaron Krinsky',
'Matt Candeloro',
'Matt Clarke',
'matt lyon',
'Meaghan Denomme',
'Meike',
'Meredith J Powell',
'Michael B Wells',
'Michael LaHood',
'Michelle Furnace',
'Mike Damewood',
'Miss Jo Gifford',
'Mohamed Karim Ben Ali',
'Morty Alman',
'mynameismonkey',
'Name',
'Nathan Maharaj',
'Nell Waters',
'Nicholas Carella',
'Nick Coombe',
'Nina Fehren',
'Norah Murphy',
'Pat Kelly',
'Paul Viafora',
'Paulo Costanzo',
'Phillip Robbins',
'Rachael Kelley',
'Rasmus Slotø',
'Reese Mankenberg',
'Richard and Erika',
'Rob Kelly',
'Robb Webster',
'Robi Vanos',
'Ruain Flanagan',
'Ryan Freeman',
'Samantha Rader',
'Samuel Johnson',
'Sara F',
'Sarah Feeley',
'sarah hardy',
'Sara Fuss',
'Scott Thompson',
'Sean Rinn',
'Simon Worley',
'Slogan6929',
'Sonja Di Giulio',
'sonja rasula',
'Stephen Breen',
'Stephen Dunn',
'steve and anne moreau',
'Tammy Milbury',
'Teddy Sears',
'Todd Mazer',
'Tom De Iulis',
'Tony Haofu',
'Tracy McDonald',
'Valeska Matziol',
'Victoria Sights',
'William Flynn',
'Zandy O Ariss',
]

